package sk.upjs.paz1c.nezabudal.gui.forms;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Window;
import sk.upjs.paz1c.nezabudal.entity.Category;
import sk.upjs.paz1c.nezabudal.entity.Item;
import sk.upjs.paz1c.nezabudal.entity.Loan;
import sk.upjs.paz1c.nezabudal.gui.models.CategoryComboBoxModel;
import sk.upjs.paz1c.nezabudal.gui.models.ItemTableModel;
import sk.upjs.paz1c.nezabudal.managers.LoanManager;
import sk.upjs.paz1c.nezabudal.other.GuiObjectFactory;
import sk.upjs.paz1c.nezabudal.other.ObjectFactory;
import sk.upjs.paz1c.nezabudal.other.Validator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mikey
 */
public class RemembrallForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RemembrallForm() {
        initComponents();
        setTitle("Nezabudal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jDialog1 = new javax.swing.JDialog();
        addCategoryButton = new javax.swing.JButton();
        removeCategoryButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        removeLoanButton = new javax.swing.JButton();
        lentByMeCheckBox = new javax.swing.JCheckBox();
        lentToMeCheckBox = new javax.swing.JCheckBox();
        loanLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        removeItemButton = new javax.swing.JButton();
        addLoanButton = new javax.swing.JButton();
        notLentCheckBox = new javax.swing.JCheckBox();
        categoryComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        editCategoryButton = new javax.swing.JButton();
        editItemButton = new javax.swing.JButton();
        SummaryjButton1 = new javax.swing.JButton();
        borrowedjButton1 = new javax.swing.JButton();
        BorowwerFormjButton1 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remembrall");
        setAutoRequestFocus(false);

        addCategoryButton.setText("Pridaj kategóriu");
        addCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryButtonActionPerformed(evt);
            }
        });

        removeCategoryButton.setText("Odstráň kategóriu");
        removeCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCategoryButtonActionPerformed(evt);
            }
        });

        addItemButton.setText("Pridaj predmet");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        removeLoanButton.setText("Odstráň pôžičku");
        removeLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLoanButtonActionPerformed(evt);
            }
        });

        lentByMeCheckBox.setSelected(true);
        lentByMeCheckBox.setText("Požičal som");
        lentByMeCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lentByMeCheckBoxMousePressed(evt);
            }
        });
        lentByMeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lentByMeCheckBoxActionPerformed1(evt);
                lentByMeCheckBoxActionPerformed(evt);
            }
        });

        lentToMeCheckBox.setSelected(true);
        lentToMeCheckBox.setText("Požičali mi");
        lentToMeCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lentToMeCheckBoxStateChanged(evt);
            }
        });
        lentToMeCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lentToMeCheckBoxMousePressed(evt);
            }
        });
        lentToMeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lentToMeCheckBoxActionPerformed(evt);
            }
        });

        loanLabel.setText("Pôžička");

        categoryLabel.setText("Kategória");

        removeItemButton.setText("Odstráň predmet");
        removeItemButton.setToolTipText("");
        removeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButtonActionPerformed(evt);
            }
        });

        addLoanButton.setText("Pridaj pôžičku");
        addLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoanButtonActionPerformed(evt);
            }
        });

        notLentCheckBox.setSelected(true);
        notLentCheckBox.setText("Nepožičané");
        notLentCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notLentCheckBoxMousePressed(evt);
            }
        });
        notLentCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notLentCheckBoxActionPerformed(evt);
            }
        });

        categoryComboBox.setModel(GuiObjectFactory.INSTANCE.getCategoryComboBoxModel());
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });
        categoryComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                categoryComboBoxPropertyChange(evt);
            }
        });

        itemTable.setModel(new ItemTableModel(getSelectedCategory()));
        itemTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                itemTableMouseMoved(evt);
            }
        });
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        editCategoryButton.setText("Uprav kategóriu");
        editCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryButtonActionPerformed(evt);
            }
        });

        editItemButton.setText("Uprav predmet");
        editItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editItemButtonActionPerformed(evt);
            }
        });

        SummaryjButton1.setText("Mesačná sumarizácia");
        SummaryjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryjButton1ActionPerformed(evt);
            }
        });

        borrowedjButton1.setText("Kto mi dlží ?");
        borrowedjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowedjButton1ActionPerformed(evt);
            }
        });

        BorowwerFormjButton1.setText("Čo ja dlžím ?");
        BorowwerFormjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorowwerFormjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lentByMeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lentToMeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notLentCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(removeCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(addItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(editItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(addLoanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(removeLoanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(SummaryjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrowedjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BorowwerFormjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryButton)
                    .addComponent(removeCategoryButton)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCategoryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lentToMeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lentByMeCheckBox)
                    .addComponent(notLentCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addItemButton)
                        .addGap(11, 11, 11)
                        .addComponent(removeItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editItemButton)
                        .addGap(10, 10, 10)
                        .addComponent(addLoanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeLoanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BorowwerFormjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrowedjButton1)
                        .addGap(39, 39, 39)
                        .addComponent(SummaryjButton1)
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lentByMeCheckBoxActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lentByMeCheckBoxActionPerformed1

    }//GEN-LAST:event_lentByMeCheckBoxActionPerformed1

    private void lentByMeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lentByMeCheckBoxActionPerformed
        itemTableRefresh();

    }//GEN-LAST:event_lentByMeCheckBoxActionPerformed

    private void lentByMeCheckBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lentByMeCheckBoxMousePressed
//        if (!lentToMeCheckBox.isSelected() && !notLentCheckBox.isSelected()) {
//            lentByMeCheckBox.setSelected(false);
//        }
        itemTableRefresh();
    }//GEN-LAST:event_lentByMeCheckBoxMousePressed

    private void lentToMeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lentToMeCheckBoxActionPerformed
        itemTableRefresh();
    }//GEN-LAST:event_lentToMeCheckBoxActionPerformed

    private void lentToMeCheckBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lentToMeCheckBoxMousePressed
//        if (!lentByMeCheckBox.isSelected() && !notLentCheckBox.isSelected()) {
//            lentToMeCheckBox.setSelected(false);
//        }
        itemTableRefresh();
    }//GEN-LAST:event_lentToMeCheckBoxMousePressed

    private void addCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryButtonActionPerformed
        CategoryDialog categoryForm = new CategoryDialog(this, true);
        categoryForm.setVisible(true);

        categoryComboBoxRefresh();
    }//GEN-LAST:event_addCategoryButtonActionPerformed

    private void notLentCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notLentCheckBoxActionPerformed
        itemTableRefresh();
    }//GEN-LAST:event_notLentCheckBoxActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void removeCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCategoryButtonActionPerformed
        String validation = Validator.validateCategoryCount();

        if (validation != null) {
            WarningDialog warningDialog = new WarningDialog(this, true, validation);
            warningDialog.setVisible(true);
        } else {
            CategoryRemoveDialog categoryRemoveDialog = new CategoryRemoveDialog(this, true);
            categoryRemoveDialog.setVisible(true);
            categoryComboBoxRefresh();
        }
    }//GEN-LAST:event_removeCategoryButtonActionPerformed

    private void removeLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLoanButtonActionPerformed
        String validation = Validator.validateLoanCount();
        if (validation != null) {
            WarningDialog warningDialog = new WarningDialog(this, true, validation);
            warningDialog.setVisible(true);
        } else {
            LoanRemoveDialog loanRemoveDialog = new LoanRemoveDialog(this, true);
//            if (getSelectedItem().isIsBorrowed()) {
//                loanRemoveDialog.setSelectedLoan(getSelectedItem());
//            }
            loanRemoveDialog.setVisible(true);
            itemTableRefresh();
        }
    }//GEN-LAST:event_removeLoanButtonActionPerformed

    private void addLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoanButtonActionPerformed

        LoanDialog loanDialog = new LoanDialog(this, true);
        loanDialog.setVisible(true);

        itemTableRefresh();
    }//GEN-LAST:event_addLoanButtonActionPerformed

    private void removeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButtonActionPerformed
        String validation = Validator.validateItemCount();
        if (validation != null) {
            WarningDialog warningDialog = new WarningDialog(this, true, validation);
            warningDialog.setVisible(true);
        } else {
            ItemRemoveDialog itemRemoveDialog = new ItemRemoveDialog(this, true, getSelectedItem());
            itemRemoveDialog.setVisible(true);
            itemTableRefresh();
        }
    }//GEN-LAST:event_removeItemButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // NetBeans is stupid, this is addLoanButtonActionPerformed !!!!!

        ItemDialog loanDialog = new ItemDialog(this, true);
        loanDialog.setVisible(true);
        itemTableRefresh();
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void editCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryButtonActionPerformed
        CategoryDialog kategoriaForm = new CategoryDialog(this, true, getSelectedCategory());
        kategoriaForm.setVisible(true);

        itemTableRefresh();
        categoryComboBoxRefresh();
    }//GEN-LAST:event_editCategoryButtonActionPerformed


    private void categoryComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_categoryComboBoxPropertyChange
        itemTableRefresh();
        // System.out.println("refresh + " +" @RemembrallForm");
    }//GEN-LAST:event_categoryComboBoxPropertyChange

    private void editItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editItemButtonActionPerformed

        Item item = getSelectedItem();
        if (item == null) {
            WarningDialog warningDialog = new WarningDialog(this, true, "Označ predmet");
            warningDialog.setVisible(true);
        } else {
            ItemDialog itemDialog = new ItemDialog(this, true, item);
            itemDialog.setVisible(true);
            itemTableRefresh();
        }
    }//GEN-LAST:event_editItemButtonActionPerformed

    private void itemTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMousePressed
        if (evt.getClickCount() == 2) {
            int riadok = itemTable.getSelectedRow();
            Item item = ((ItemTableModel) itemTable.getModel()).getItemAt(riadok);

            LoanManager loanManager = ObjectFactory.INSTANCE.getLoanManager();
            Loan loan = loanManager.getByItem(item);
            LoanDialog loanDialog;
            if (loan == null) {
                loanDialog = new LoanDialog(this, true);
            } else {
                loanDialog = new LoanDialog(this, true, loan);
            }
            loanDialog.setVisible(true);
            itemTableRefresh();
        }
    }//GEN-LAST:event_itemTableMousePressed

    private void itemTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTableMouseMoved

    private void notLentCheckBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notLentCheckBoxMousePressed
//        if (!lentByMeCheckBox.isSelected() && !lentToMeCheckBox.isSelected()) {
//            notLentCheckBox.setSelected(false);
//        }
        itemTableRefresh();
    }//GEN-LAST:event_notLentCheckBoxMousePressed

    private void lentToMeCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lentToMeCheckBoxStateChanged

    }//GEN-LAST:event_lentToMeCheckBoxStateChanged

    private void SummaryjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryjButton1ActionPerformed
        SummaryForm summaryForm = new SummaryForm(this, true);
        summaryForm.setVisible(true);

        itemTableRefresh();
    }//GEN-LAST:event_SummaryjButton1ActionPerformed

    private void borrowedjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowedjButton1ActionPerformed
        BorrowedForm borrowedForm = new BorrowedForm(this, true);
        borrowedForm.setVisible(true);

        itemTableRefresh();
    }//GEN-LAST:event_borrowedjButton1ActionPerformed

    private void BorowwerFormjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorowwerFormjButton1ActionPerformed
        BorrowerForm borrowerForm = new BorrowerForm(this, true);
        borrowerForm.setVisible(true);

        itemTableRefresh();
    }//GEN-LAST:event_BorowwerFormjButton1ActionPerformed

    private Category getSelectedCategory() {
        return (Category) getComboBoxModel().getSelectedItem();
    }

    private void categoryComboBoxRefresh() {
        getComboBoxModel().refresh();
    }

    private CategoryComboBoxModel getComboBoxModel() {
        return (CategoryComboBoxModel) categoryComboBox.getModel();
    }

    private Item getSelectedItem() {
        int selectedRow = itemTable.getSelectedRow();
        if (selectedRow == -1) {
            return null;
        } else {
            return getItemTableModel().getItemAt(selectedRow);
        }
    }

    private void itemTableRefresh() {
        getItemTableModel().refresh(lentByMeCheckBox.isSelected(), lentToMeCheckBox.isSelected(),
                notLentCheckBox.isSelected(), getSelectedCategory());
    }

    private ItemTableModel getItemTableModel() {
        return (ItemTableModel) itemTable.getModel();
    }

    static void setPositionMiddle(Window parent, Window child) {
        Dimension dimParent = parent.getSize();
        Dimension dimThis = child.getSize();

        Point point = parent.getLocation();
        point.setLocation(point.getX() + dimParent.getWidth() / 2 - dimThis.getWidth() / 2,
                point.getY() + dimParent.getHeight() / 2 - dimThis.getHeight() / 2);
        child.setLocation(point);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //  javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemembrallForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorowwerFormjButton1;
    private javax.swing.JButton SummaryjButton1;
    private javax.swing.JButton addCategoryButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addLoanButton;
    private javax.swing.JButton borrowedjButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Category> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton editCategoryButton;
    private javax.swing.JButton editItemButton;
    private javax.swing.JTable itemTable;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox lentByMeCheckBox;
    private javax.swing.JCheckBox lentToMeCheckBox;
    private javax.swing.JLabel loanLabel;
    private javax.swing.JCheckBox notLentCheckBox;
    private javax.swing.JButton removeCategoryButton;
    private javax.swing.JButton removeItemButton;
    private javax.swing.JButton removeLoanButton;
    // End of variables declaration//GEN-END:variables

}
