/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.paz1c.nezabudal.gui.forms;

import java.util.List;
import sk.upjs.paz1c.nezabudal.entity.Category;
import sk.upjs.paz1c.nezabudal.entity.Month;
import sk.upjs.paz1c.nezabudal.other.GuiObjectFactory;
import sk.upjs.paz1c.nezabudal.entity.Loan;
import sk.upjs.paz1c.nezabudal.entity.Item;
import sk.upjs.paz1c.nezabudal.other.ObjectFactory;


/**
 *
 * @author erika
 */
    
public class SummaryForm extends javax.swing.JDialog {
    
    private List<Loan> loans = ObjectFactory.INSTANCE.getLoanManager().getLoans();
    private List<Item> items = ObjectFactory.INSTANCE.getItemManager().getItems();
    private List<Category> categories = ObjectFactory.INSTANCE.getCategoryManager().getCategories();
    
    /**
     * Creates new form SummaryForm
     */
    public SummaryForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private int getMonthFromLoan(){
        int mesiac = -1;
        for(Loan loan:loans){
            mesiac = loan.getStartDate().getMonthValue();
            return mesiac;
        }
        return mesiac;
    }
    
    private int showIsBorrowed(){
        int pocet = 0;
        for(Item item : items){
            if(item.getCategory().getId() == CategoryjComboBox1.getSelectedIndex()+1){
                if(this.getMonthFromLoan() == MonthComboBox1.getSelectedIndex()+1){
                    if(item.isIsBorrowed()== false){
                        if(CategoryjComboBox1.getSelectedIndex() == 2){
                            int cena = Integer.parseInt(item.getName());
                            System.out.println(item.getName());
                            pocet+=cena;  
                        } else {
                            pocet++;
                        }
                    }
                }
            }
        }
        
        return pocet;
    }
    
    
    private int showBorrowed(){
        int pocet = 0;        
        for(Item item : items){
            if(item.getCategory().getId() == CategoryjComboBox1.getSelectedIndex()+1){
                if(this.getMonthFromLoan() == MonthComboBox1.getSelectedIndex()+1){
                    if(item.isIsBorrowed()== true){
                        if(CategoryjComboBox1.getSelectedIndex() == 2){
                            int cena = Integer.parseInt(item.getName());
                            System.out.println(item.getName());
                            pocet+=cena;  
                        } else {
                            pocet++;
                        }
                    }
                }
            }
        }
        return pocet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SummaryjLabel1 = new javax.swing.JLabel();
        MonthComboBox1 = new javax.swing.JComboBox<>();
        MonthjLabel1 = new javax.swing.JLabel();
        CategoryjLabel1 = new javax.swing.JLabel();
        IsBorrowedjLabel1 = new javax.swing.JLabel();
        BorrowedjLabel1 = new javax.swing.JLabel();
        HodnotaIsBorrowedjLabel1 = new javax.swing.JLabel();
        HodnotaBorrowedjLabel2 = new javax.swing.JLabel();
        CategoryjComboBox1 = new javax.swing.JComboBox<>();
        refreshjButton1 = new javax.swing.JButton();
        countjLabel2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SummaryjLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SummaryjLabel1.setText("Sumarizácia");

        MonthComboBox1.setModel(GuiObjectFactory.INSTANCE.getMonthComboBoxModel());
        MonthComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthComboBox1ActionPerformed(evt);
            }
        });

        MonthjLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MonthjLabel1.setText("Mesiac");

        CategoryjLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CategoryjLabel1.setText("Kategória");

        IsBorrowedjLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IsBorrowedjLabel1.setText("Požíčal som");

        BorrowedjLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BorrowedjLabel1.setText("Mám požíčané");

        HodnotaIsBorrowedjLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        HodnotaBorrowedjLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        CategoryjComboBox1.setModel(GuiObjectFactory.INSTANCE.getCategoryComboBoxModel());
        CategoryjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryjComboBox1ActionPerformed(evt);
            }
        });

        refreshjButton1.setText("Refresh");
        refreshjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButton1ActionPerformed(evt);
            }
        });

        countjLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CategoryjLabel1)
                            .addComponent(MonthjLabel1)
                            .addComponent(IsBorrowedjLabel1)
                            .addComponent(BorrowedjLabel1))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MonthComboBox1, 0, 111, Short.MAX_VALUE)
                            .addComponent(CategoryjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HodnotaBorrowedjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(countjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HodnotaIsBorrowedjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshjButton1)
                            .addComponent(SummaryjLabel1))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SummaryjLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthjLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryjLabel1)
                    .addComponent(CategoryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(refreshjButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrowedjLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IsBorrowedjLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HodnotaIsBorrowedjLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countjLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HodnotaBorrowedjLabel2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryjComboBox1ActionPerformed

    private void MonthComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthComboBox1ActionPerformed

    private void refreshjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButton1ActionPerformed
        jLabel2.setText(Integer.toString(showIsBorrowed()));
        jLabel3.setText(Integer.toString(showBorrowed()));
    }//GEN-LAST:event_refreshjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SummaryForm dialog = new SummaryForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BorrowedjLabel1;
    private javax.swing.JComboBox<Category> CategoryjComboBox1;
    private javax.swing.JLabel CategoryjLabel1;
    private javax.swing.JLabel HodnotaBorrowedjLabel2;
    private javax.swing.JLabel HodnotaIsBorrowedjLabel1;
    private javax.swing.JLabel IsBorrowedjLabel1;
    private javax.swing.JComboBox<Month> MonthComboBox1;
    private javax.swing.JLabel MonthjLabel1;
    private javax.swing.JLabel SummaryjLabel1;
    private javax.swing.JLabel countjLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton refreshjButton1;
    // End of variables declaration//GEN-END:variables
}
