package sk.upjs.ics.paz1c.nemocnica;

public class DetailForm extends javax.swing.JFrame {

    public DetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okDetailButton = new javax.swing.JButton();
        detailLabel = new javax.swing.JLabel();
        lekarDetailjLabel = new javax.swing.JLabel();
        pacientDetailjLabel = new javax.swing.JLabel();
        menoLekarDetailjLabel = new javax.swing.JLabel();
        priezviskoLekarDetailjLabel = new javax.swing.JLabel();
        specLekarDetailjLabel = new javax.swing.JLabel();
        menoPacientDetailjLabel = new javax.swing.JLabel();
        priezviskoPacientDetailjLabel = new javax.swing.JLabel();
        vekPacientDetailjLabel = new javax.swing.JLabel();
        diagnozaDetailjLabel = new javax.swing.JLabel();
        diagnozaNazovDetailjLabel = new javax.swing.JLabel();
        liekDetailjLabel = new javax.swing.JLabel();
        nazovLiekDetailjLabel = new javax.swing.JLabel();
        upravitjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        okDetailButton.setText("OK");
        okDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okDetailButtonActionPerformed(evt);
            }
        });

        detailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        detailLabel.setText("Detail záznamu :");

        lekarDetailjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lekarDetailjLabel.setText("Lekár ");

        pacientDetailjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pacientDetailjLabel.setText("Pacient ");

        menoLekarDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menoLekarDetailjLabel.setText("Meno :");

        priezviskoLekarDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priezviskoLekarDetailjLabel.setText("Priezvisko :");

        specLekarDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        specLekarDetailjLabel.setText("Špecializácia :");

        menoPacientDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menoPacientDetailjLabel.setText("Meno : ");

        priezviskoPacientDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priezviskoPacientDetailjLabel.setText("Priezvisko :");

        vekPacientDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vekPacientDetailjLabel.setText("Vek :");

        diagnozaDetailjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diagnozaDetailjLabel.setText("Diagnóza ");

        diagnozaNazovDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diagnozaNazovDetailjLabel.setText("Názov :");

        liekDetailjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        liekDetailjLabel.setText("Liek ");

        nazovLiekDetailjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nazovLiekDetailjLabel.setText("Názov :");

        upravitjButton.setText("UPRAVIŤ");
        upravitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravitjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lekarDetailjLabel)
                    .addComponent(detailLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menoLekarDetailjLabel)
                                    .addComponent(priezviskoLekarDetailjLabel)
                                    .addComponent(specLekarDetailjLabel)
                                    .addComponent(diagnozaDetailjLabel)
                                    .addComponent(diagnozaNazovDetailjLabel))
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(upravitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priezviskoPacientDetailjLabel)
                            .addComponent(menoPacientDetailjLabel)
                            .addComponent(vekPacientDetailjLabel)
                            .addComponent(liekDetailjLabel)
                            .addComponent(nazovLiekDetailjLabel)
                            .addComponent(okDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pacientDetailjLabel))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lekarDetailjLabel)
                    .addComponent(pacientDetailjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menoLekarDetailjLabel)
                    .addComponent(menoPacientDetailjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priezviskoPacientDetailjLabel)
                    .addComponent(priezviskoLekarDetailjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specLekarDetailjLabel)
                    .addComponent(vekPacientDetailjLabel))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnozaDetailjLabel)
                    .addComponent(liekDetailjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnozaNazovDetailjLabel)
                    .addComponent(nazovLiekDetailjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okDetailButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(upravitjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upravitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravitjButtonActionPerformed
        UpravitForm upravitForm = new UpravitForm();
        upravitForm.setVisible(true);
        upravitForm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_upravitjButtonActionPerformed

    private void okDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okDetailButtonActionPerformed
       dispose();
    }//GEN-LAST:event_okDetailButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailLabel;
    private javax.swing.JLabel diagnozaDetailjLabel;
    private javax.swing.JLabel diagnozaNazovDetailjLabel;
    private javax.swing.JLabel lekarDetailjLabel;
    private javax.swing.JLabel liekDetailjLabel;
    private javax.swing.JLabel menoLekarDetailjLabel;
    private javax.swing.JLabel menoPacientDetailjLabel;
    private javax.swing.JLabel nazovLiekDetailjLabel;
    private javax.swing.JButton okDetailButton;
    private javax.swing.JLabel pacientDetailjLabel;
    private javax.swing.JLabel priezviskoLekarDetailjLabel;
    private javax.swing.JLabel priezviskoPacientDetailjLabel;
    private javax.swing.JLabel specLekarDetailjLabel;
    private javax.swing.JButton upravitjButton;
    private javax.swing.JLabel vekPacientDetailjLabel;
    // End of variables declaration//GEN-END:variables
}
