package sk.upjs.ics.paz1c.nemocnica;

import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

public class DruhyForm extends javax.swing.JFrame {

    private ZaznamTableModel model;
    
    public DruhyForm() {
        initComponents(); 
        aktualizovatZaznamy();
    }
    
    private void aktualizovatZaznamy() {
        // ziskanie modelu
       model = (ZaznamTableModel) zaznamyjTable.getModel();        
        // aktualizovanie modelu
        model.aktualizovat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zaznamyLabel = new javax.swing.JLabel();
        pridatButton = new javax.swing.JButton();
        zmazatButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        refreshjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        zaznamyjTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zaznamyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        zaznamyLabel.setText("Záznamy");

        pridatButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pridatButton.setText("PRIDAŤ");
        pridatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatButtonActionPerformed(evt);
            }
        });

        zmazatButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zmazatButton.setText("ZMAZAŤ");
        zmazatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazatButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("NÁPOVEDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        refreshjButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refreshjButton.setText("REFRESH");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        zaznamyjTable.setModel(new ZaznamTableModel());
        zaznamyjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zaznamyjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(zaznamyjTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(zaznamyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(refreshjButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(pridatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zmazatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshjButton)
                    .addComponent(zaznamyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pridatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zmazatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // zobrazenie pridat formu
    private void pridatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatButtonActionPerformed
        PridatForm pridatForm = new PridatForm();
        pridatForm.setVisible(true);
        pridatForm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_pridatButtonActionPerformed

    // zmazanie zaznamu, je potrebne oznacit zaznam
    private void zmazatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazatButtonActionPerformed
        if(zaznamyjTable.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Je potrebné najskôr označiť záznam.");
        } else {
            // vybratie zaznamu v tabulke
            int riadok = zaznamyjTable.getSelectedRow();
            Zaznam zaznam = ((ZaznamTableModel) zaznamyjTable.getModel()).getZaznamAt(riadok);
            // okno ano nie
            int odpoved = JOptionPane.YES_NO_OPTION;
            int otazka = JOptionPane.showConfirmDialog(this, "Ste si istý?", "Vymazať" ,odpoved);
            // ak je odpoved ano, tak vymaze zoznam a refreshne list zoznamov
            if(otazka == 0){            
                DaoFactory.INSTANCE.getZaznamDao().vymazZaznam(zaznam);
                model.aktualizovat();
             }
        }
    }//GEN-LAST:event_zmazatButtonActionPerformed

    // napoveda
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Všetky záznamy, ktoré sa nachádzajú v systéme. \n"
                                    +"Po dvojkliknutí na záznam sa Vám zobrazí podrobné informácie o zázname.  \n"
                                    + "Tlačidlo pridať Vám umožní pridať nový záznam "
                                        + "a tlačidlo vymazať Vám umožní vymazať aktuálny vybratý záznam. \n"
                                     + "Po pridaní záznamu je potrebné stlačiť tlačidlo refresh pre zobrazenie nového záznamu.");
    }//GEN-LAST:event_jButton1ActionPerformed

    // refresh tabulky zoznamov 
    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        model.aktualizovat();
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void zaznamyjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zaznamyjTableMouseClicked
        // ked sa dvakrat klikne na nejaky riadok v tabulke, tak sa zobrazi detail danneho zaznamu
        if ( evt.getClickCount() == 2) {
            int riadok = zaznamyjTable.getSelectedRow();
            Zaznam zaznam = ((ZaznamTableModel) zaznamyjTable.getModel()).getZaznamAt(riadok);
            
            DetailForm detailForm = new DetailForm();
            detailForm.detailZaznam(zaznam);
            detailForm.setVisible(true);
            
            aktualizovatZaznamy();
        }
    }//GEN-LAST:event_zaznamyjTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DruhyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DruhyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DruhyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DruhyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DruhyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pridatButton;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JLabel zaznamyLabel;
    private javax.swing.JTable zaznamyjTable;
    private javax.swing.JButton zmazatButton;
    // End of variables declaration//GEN-END:variables
}
